### ISSUE TITLE
Alternate nav bar for mobile devices

### ISSUE THREAD

**Issue by benhsm** [opportunity-hack/evs#2]
The nav bar currently gets cut off on narrower screens. There's a need for a collapsible/expandable menu to be displayed on such devices.

**Comment by parkerdavis1** [comment]
I could work on getting everything more mobile responsive. I generally use iPhone 5/SE as the minimum reasonable screen size to account for (320x568).

**Comment by benhsm** [comment]
If you're interested in doing that, I think it would certainly be helpful. It might be quite challenging to get the admin table and calendar views to have good UX on mobile devices, and that might actually be a non-goal for us.

**Comment by parkerdavis1** [comment]
You’re right that the calendar might be too much of a project to optimize for mobile but I do think some simple changes could make most pages and forms be more usable on mobile.

Question: 
Have you considered using First Name & Last Name (rather than just 'Name') for identifying users? Specifying and requiring both would ensure users include both which I’m guessing would be essential for Girard’s admin purposes.

This would also simplify the name display for `UserDropdown`. It is set to display a users full ‘Name’  which can be quite long. This can and should be dealt with in [other ways](https://defensivecss.dev/tip/long-content) of course, but it does seem like an important piece of admin information regardless of the UI.

**Comment by gregv** [comment]
![image](https://github.com/opportunity-hack/evs/assets/6913307/f638f40f-206c-480b-b0c0-aa7789c3c0f4)
@parkerdavis1 solved this through #24 

Closing
