### ISSUE TITLE
Bug: Opening ToS and PP pages glitch on Page Load

### ISSUE THREAD

**Issue by leonkoech** [opportunity-hack/evs#72]
### Please Note:
- Probably Low Priority

When navigating to the [Terms of Service](https://thebarn.trottrack.org/tos) or [Privacy Policy](https://thebarn.trottrack.org/privacy) on the onboarding page, a brief flash of unstyled content appears for approximately 0.5(?) seconds before the correct styling is applied.
This visual glitch occurs consistently on every page load.

## Steps to Reproduce

1. Access [Terms of Service](https://thebarn.trottrack.org/tos) or [Privacy Policy](https://thebarn.trottrack.org/privacy) on the onboarding page.
2. Observe the glitch occurring consistently on refresh

## Expected Behavior:

The page should load with its intended styling immediately, without any unstyled content flashes.

## Browser and Device Information:

Browser: Chrome
Operating System: Windows
Device: Laptop

**Comment by gregv** [comment]
Fixed in prod (also added footer links at the bottom) - closing
https://thebarn.trottrack.org/tos
https://thebarn.trottrack.org/privacy

![image](https://github.com/opportunity-hack/evs/assets/6913307/07c563e5-0d0d-4a93-af90-ea9c4c0cb2ea)
![image](https://github.com/opportunity-hack/evs/assets/6913307/553f75a8-8123-4fce-91ef-428057434359)
